// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muysdfoszppwodrnyptg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eXNkZm9zenBwd29kcm55cHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzM1MzAsImV4cCI6MjA1ODIwOTUzMH0.oZDa3CUEc69L7QpJ7GYex1LcS9CiCzPDT1iQcBDeVgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);