
name: Visual Regression Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/components/**'
      - 'src/tests/visual/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/components/**'
      - 'src/tests/visual/**'

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create baseline if needed
        run: |
          if [ ! -d "src/tests/__image_snapshots__" ]; then
            npm run test:visual -- --updateSnapshot
          fi
      
      - name: Run visual regression tests
        run: npm run test:visual
      
      - name: Upload diff images on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: image-snapshots-diff
          path: src/tests/__image_snapshots__/__diff_output__
          retention-days: 7

